apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-dep
  labels:
    app: springboot-app
spec:
 replicas: 1
 selector:
  matchLabels:
    app: springboot-app
 template:
  labels:
    app: springboot-app
  spec:
   containers: 
   - name: springboot-container
     image: akbarmohd/webapp:16
     ports:
     - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: java-svc
spec:
  selector:
    app: springboot-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  type: NodePort
    